///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace jenkins_ranorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The check_for_3 recording.
    /// </summary>
    [TestModule("1692cc41-210e-4461-91a6-41c3fd362c4b", ModuleType.Recording, 1)]
    public partial class Check_for_3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the jenkins_ranorexRepository repository.
        /// </summary>
        public static jenkins_ranorexRepository repo = jenkins_ranorexRepository.Instance;

        static Check_for_3 instance = new Check_for_3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Check_for_3()
        {
            path_to_app_local = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Check_for_3 Instance
        {
            get { return instance; }
        }

#region Variables

        string _path_to_app_local;

        /// <summary>
        /// Gets or sets the value of variable path_to_app_local.
        /// </summary>
        [TestVariable("831076f4-96f2-457e-bac2-41d9af14292e")]
        public string path_to_app_local
        {
            get { return _path_to_app_local; }
            set { _path_to_app_local = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application with file name from variable $path_to_app_local in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication(path_to_app_local, "", "", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'MainWindow'", repo.MainWindow.SelfInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.MainWindow.SelfInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.IdTxtBox' at 4;9.", repo.MainWindow.IdTxtBoxInfo, new RecordItemIndex(2));
            repo.MainWindow.IdTxtBox.Click("4;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4') on item 'MainWindow.IdTxtBox'.", repo.MainWindow.IdTxtBoxInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.MainWindow.IdTxtBoxInfo, "Text", "4");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.IdTxtBox' at Center.", repo.MainWindow.IdTxtBoxInfo, new RecordItemIndex(4));
            repo.MainWindow.IdTxtBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'MainWindow'.", repo.MainWindow.SelfInfo, new RecordItemIndex(5));
            Host.Current.CloseApplication(repo.MainWindow.Self, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
